<%@page import="FUZZY.SQLconnection"%>
<%@page import="java.sql.ResultSet"%>
<%@page import="java.sql.Connection"%>
<%@page import="java.sql.Statement"%>
<%@page import="java.sql.PreparedStatement"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%
    String fid = request.getParameter("fid");
    String hash1 = request.getParameter("hash");
%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>TPA Proof Verification | Fuzzy Auditing</title>
  <link rel="stylesheet" href="css/cyber_theme.css">
  <script>
    function verifyProofMatch(event) {
      event.preventDefault();
      var h1 = document.getElementById('pwd1').value.trim();
      var h2 = document.getElementById('pwd2').value.trim();
      var resultDiv = document.getElementById('verification-result');
      
      if (h1 && h2 && h1 === h2) {
        resultDiv.innerHTML = '<div class="alert-banner success" style="margin-top: 20px;">' +
          '<span>&#10004;</span>' +
          '<div><strong>TPA AUDIT VERIFIED (PASS):</strong> The cryptographic proof hash generated by Cloud Server matches the original document hash with 100% mathematical fidelity. Data integrity confirmed!</div>' +
          '</div>';
      } else {
        resultDiv.innerHTML = '<div class="alert-banner error" style="margin-top: 20px;">' +
          '<span>&#9888;</span>' +
          '<div><strong>TPA AUDIT INTEGRITY BREACH (FAIL):</strong> Proof hash mismatch detected. Potential cloud corruption, tampering, or Byzantine server behavior!</div>' +
          '</div>';
      }
    }
  </script>
</head>
<body>

  <!-- Top Navigation Bar -->
  <nav class="cyber-navbar">
    <div class="app-container nav-wrapper">
      <a href="TPA_home.jsp" class="brand-logo">
        <div class="brand-icon" style="background: linear-gradient(135deg, var(--amber-primary), #d97706);">T</div>
        <div class="brand-text">
          <h1>TPA AUDITING SUITE</h1>
          <p>Proof Verification</p>
        </div>
      </a>
      <ul class="nav-links">
        <li><a href="TPA_home.jsp">Dashboard</a></li>
        <li><a href="proof_Check.jsp">&larr; Back to Proof List</a></li>
      </ul>
    </div>
  </nav>

  <!-- Main Container -->
  <main class="app-container hero-section">
    <div style="max-width: 620px; margin: 30px auto;">

      <div class="cyber-card">
        <div class="card-header">
          <h3>&#128269; Third Party Public Proof Verification</h3>
          <span class="role-badge tpa">Auditor Match</span>
        </div>
        <div class="card-body">
          <%
              Connection con = null;
              PreparedStatement ps = null;
              ResultSet rs = null;
              try {
                  con = SQLconnection.getconnection();
                  if (con != null) {
                      ps = con.prepareStatement("SELECT * FROM fileupload WHERE filekey = ?");
                      ps.setString(1, fid != null ? fid.trim() : "");
                      rs = ps.executeQuery();
                      if (rs.next()) {
                          String storedHash = rs.getString("hashcode");
          %>
          <form onsubmit="verifyProofMatch(event);">
            
            <div class="form-group">
              <label for="fileId">File Key / Identifier</label>
              <input id="fileId" type="text" name="username" class="form-control" value="<%= fid != null ? fid : "" %>" readonly style="font-family: var(--font-mono); color: var(--cyan-glow);">
            </div>

            <div class="form-group">
              <label for="pwd1">Cloud Auditing Proof Hash (Received from Cloud Server)</label>
              <input id="pwd1" type="text" name="pwd1" class="form-control" value="<%= hash1 != null ? hash1 : "" %>" readonly style="font-family: var(--font-mono); color: var(--emerald-glow);">
            </div>

            <div class="form-group">
              <label for="pwd2">Original Upload Hash (Recorded in Database)</label>
              <input id="pwd2" type="text" name="pwd2" class="form-control" value="<%= storedHash %>" readonly style="font-family: var(--font-mono); color: #fbbf24;">
            </div>

            <div style="margin-top: 24px; display: flex; gap: 12px;">
              <button type="submit" class="btn btn-cyber" style="flex: 1; background: linear-gradient(135deg, var(--amber-primary), #d97706); color: #0b0f19; font-weight: 700;">
                &#9989; Execute Public Audit Verification
              </button>
              <a href="proof_Check.jsp" class="btn btn-outline">Cancel</a>
            </div>

          </form>

          <div id="verification-result"></div>

          <%
                      } else {
          %>
          <div class="alert-banner error">
            <span>&#9888;</span>
            <div>File record not found in repository.</div>
          </div>
          <%
                      }
                  }
              } catch (Exception ex) {
          %>
          <div class="alert-banner error">
            <span>&#9888;</span>
            <div>Error: <%= ex.getMessage() %></div>
          </div>
          <%
              } finally {
                  if (rs != null) try { rs.close(); } catch (Exception ignored) {}
                  if (ps != null) try { ps.close(); } catch (Exception ignored) {}
                  if (con != null) try { con.close(); } catch (Exception ignored) {}
              }
          %>
        </div>
      </div>

    </div>
  </main>

  <!-- Footer -->
  <footer class="cyber-footer">
    <div class="app-container">
      <p><strong>Department of Computer Science & Engineering</strong> &bull; R R Institute of Technology</p>
    </div>
  </footer>

</body>
</html>
