<%@page import="java.sql.ResultSet"%>
<%@page import="java.sql.Statement"%>
<%@page import="java.sql.Connection"%>
<%@page import="FUZZY.SQLconnection"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%
    String uname = (String)session.getAttribute("uname");
    String uid = (String)session.getAttribute("uid");
    if (uname == null) {
        uname = "Data Owner";
    }
%>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Audit Proofs & Verification | Fuzzy Identity Auditing</title>
  <link rel="stylesheet" href="css/cyber_theme.css">
</head>
<body>

  <!-- Top Navigation Bar -->
  <nav class="cyber-navbar">
    <div class="app-container nav-wrapper">
      <a href="User_home.jsp" class="brand-logo">
        <div class="brand-icon">U</div>
        <div class="brand-text">
          <h1>USER PORTAL</h1>
          <p><%= uname %> &bull; Integrity Proofs</p>
        </div>
      </a>
      <ul class="nav-links">
        <li><a href="User_home.jsp">Dashboard</a></li>
        <li><a href="File_Upload.jsp">Upload File</a></li>
        <li><a href="MyFiles.jsp">My Files</a></li>
        <li><a href="audit_request.jsp">Request Audit</a></li>
        <li class="active"><a href="user_check.jsp">Audit Proofs</a></li>
        <li><a href="index.jsp" style="color: var(--rose-primary);">Logout</a></li>
      </ul>
    </div>
  </nav>

  <!-- Main Container -->
  <main class="app-container hero-section">
    <div class="page-header-card">
      <div class="page-title-row">
        <div>
          <span class="role-badge emerald" style="margin-bottom: 10px;">Integrity Verification</span>
          <h2 class="page-title">Cryptographic Audit Proofs</h2>
          <p class="page-subtitle">Inspect proofs generated by the Cloud Server and execute mathematical integrity validation.</p>
        </div>
      </div>
    </div>

    <!-- Table Card -->
    <div class="cyber-card" style="margin-top: 24px;">
      <div class="card-header">
        <h3>&#9989; Generated Proof Repository</h3>
        <span class="role-badge user">User ID: <%= uid != null ? uid : "All" %></span>
      </div>
      <div class="card-body" style="padding: 0;">
        <div class="table-responsive">
          <table class="cyber-table">
            <thead>
              <tr>
                <th>Owner ID</th>
                <th>File Key</th>
                <th>Cryptographic Proof Hash</th>
                <th style="text-align: right;">Action</th>
              </tr>
            </thead>
            <tbody>
              <%
                  Connection con = SQLconnection.getconnection();
                  Statement st = con.createStatement();
                  int count = 0;
                  try {
                      String query = (uid != null && !uid.isEmpty()) ? "Select * from audit_proof where uid='" + uid + "' ORDER BY id DESC" : "Select * from audit_proof ORDER BY id DESC";
                      ResultSet rs = st.executeQuery(query);
                      while (rs.next()) {
                          count++;
              %>
              <tr>
                <td><span class="mono-code">UID-<%= rs.getString("uid") %></span></td>
                <td><span class="mono-code" style="color: var(--cyan-glow);"><%= rs.getString("filekey") %></span></td>
                <td><span class="mono-code" style="color: var(--emerald-glow);"><%= rs.getString("hashproof") %></span></td>
                <td style="text-align: right;">
                  <a href="test.jsp?fid=<%= rs.getString("filekey") %>&hash=<%= rs.getString("hashproof") %>" class="btn btn-emerald btn-sm">
                    &#9989; Verify Proof &rarr;
                  </a>
                </td>
              </tr>
              <%
                      }
                      if (count == 0) {
              %>
              <tr>
                <td colspan="4" style="text-align: center; padding: 36px; color: var(--text-muted);">
                  No audit proofs generated yet. Go to <a href="audit_request.jsp" style="color: var(--cyan-glow); font-weight: 600;">Request Audit</a> to challenge the cloud.
                </td>
              </tr>
              <%
                      }
                  } catch (Exception ex) {
              %>
              <tr>
                <td colspan="4" style="color: var(--rose-primary); padding: 20px;">Error loading proofs: <%= ex.getMessage() %></td>
              </tr>
              <%
                  }
              %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>

  <!-- Footer -->
  <footer class="cyber-footer">
    <div class="app-container">
      <p><strong>Department of Computer Science & Engineering</strong> &bull; R R Institute of Technology</p>
    </div>
  </footer>

</body>
</html>
