const db = require('./lib/db');

module.exports = async (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') return res.status(200).end();

  const action = req.query.action || (req.body && req.body.action);

  try {
    // 1. TPA Dispatches Challenge to Cloud Server (matching send_cloud.jsp)
    if (action === 'challenge') {
      const { filekey, uid } = req.body || {};
      if (!filekey) {
        return res.status(400).json({ success: false, message: 'filekey required' });
      }

      const fileRows = await db.query('SELECT * FROM fileupload WHERE filekey = ?', [filekey]);
      if (!fileRows || fileRows.length === 0) {
        return res.status(404).json({ success: false, message: 'File record not found' });
      }

      const file = fileRows[0];
      const currentTime = new Date().toISOString().replace('T', ' ').substring(0, 19);

      await db.query('UPDATE audit_request SET status = ? WHERE filekey = ?', ['Sent to Cloud', filekey]);
      await db.query(
        'INSERT INTO cloud_request (filekey, time, uid, status, hash) VALUES (?, ?, ?, ?, ?)',
        [filekey, currentTime, String(uid || file.uid), 'waiting', file.hashcode]
      );

      return res.status(200).json({
        success: true,
        message: 'TPA Challenge successfully transmitted to Cloud Storage Server.',
        filekey
      });
    }

    // 2. GET: List Proofs for TPA Verification
    if (req.method === 'GET' || action === 'proofs') {
      const proofs = await db.query('SELECT * FROM audit_proof');
      return res.status(200).json({ success: true, proofs });
    }

    // 3. POST: Execute Deterministic Proof Verification (matching proof_verify.jsp)
    if (action === 'verify') {
      const { filekey, cloudProofHash } = req.body || {};
      if (!filekey || !cloudProofHash) {
        return res.status(400).json({ success: false, message: 'filekey and cloudProofHash required' });
      }

      const fileRows = await db.query('SELECT * FROM fileupload WHERE filekey = ?', [filekey]);
      if (!fileRows || fileRows.length === 0) {
        return res.status(404).json({ success: false, message: 'File record not found in repository' });
      }

      const file = fileRows[0];
      const originalHash = file.hashcode;
      const isMatch = String(originalHash).trim() === String(cloudProofHash).trim();

      if (isMatch) {
        return res.status(200).json({
          success: true,
          verified: true,
          filekey,
          originalHash,
          cloudProofHash,
          message: 'TPA AUDIT VERIFIED (PASS): The cryptographic proof hash generated by Cloud Server matches the original document hash with 100% mathematical fidelity. Data integrity confirmed!'
        });
      } else {
        return res.status(200).json({
          success: true,
          verified: false,
          filekey,
          originalHash,
          cloudProofHash,
          message: 'TPA AUDIT INTEGRITY BREACH (FAIL): Proof hash mismatch detected. Potential cloud corruption, tampering, or Byzantine server behavior!'
        });
      }
    }

    return res.status(400).json({ success: false, message: 'Invalid action parameter' });
  } catch (err) {
    console.error('TPA operation error:', err);
    return res.status(500).json({ success: false, message: err.message });
  }
};
